[package]
name = "extern_traces_viewer"
version = "0.0.1"
edition = "2021"

build = "build.rs"

[features]
renderdoc_hooks = ["renderdoc"]

[dependencies]
eframe = "0.28.1"
egui_plot = "0.28.1"
ps4libdoc = { path = "../ps4libdoc" }
egui_tiles = "0.9.1"
rfd = "0.15.0"
clap = { version = "4.5.18", features = ["derive"] }
hex = "0.4.3"
vulkano = "0.34.1"
vulkano-shaders = "0.34.0"
renderdoc = { version = "0.11.0", optional = true }
pm4 = { path = "../pm4" }
gcn = { path = "../gcn" }
gcn_extract = { path = "../gcn_extract" }
gcn_spirv = { path = "../gcn_spirv" }
rspirv = "0.12.0"
itertools = "0.11.0"
bytemuck = { version = "1.14.0", features = ["derive"] }
anyhow = { version = "1.0.71", features = ["backtrace"] }
libc = "0.2.158"
zorder = "0.2.2"
strum = { version = "0.25.0", features = ["derive"] }
