[package]
name = "ps4libdoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
glob = "0.3.1"
anyhow = "1.0.75"
rust-embed = "8.5.0"
