[package]
name = "gcn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
anyhow = "1.0.76"
strum = { version = "0.25.0", features = ["derive"] }
gcn_internal_macros = { path = "../gcn_internal_macros" }
bits = { path = "../bits" }
bits_macros = { path = "../bits_macros" }

[dev-dependencies]
insta = { version = "1.33.0" }
glob = "0.3.1"
