[package]
name = "gcn_spirv"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
gcn = { path = "../gcn" }
pm4 = { path = "../pm4" }
bits = { path = "../bits" }
rspirv = "0.12.0"
itertools = "0.12.0"
bytemuck = "1.17.1"
vulkano = "0.34.1"

[dev-dependencies]
spirv-tools = "0.10.0"
insta = "1.39.0"
snapshot_test_utils = { path = "../snapshot_test_utils" }
byteorder = "1.5.0"
sha2 = "0.10.8"
