[package]
name = "gcn_extract"
description = "a nostd crate for extracting state from graphics submits"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
gcn = { path = "../gcn" }
bits = { path = "../bits" }
bytemuck = "1.18.0"
