[package]
name = "plugin_support"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
pm4 = { path = "../../../ps4-tools/packages/pm4" }
gcn_extract = { path = "../../../ps4-tools/packages/gcn_extract" }
gcn = { path = "../../../ps4-tools/packages/gcn" }
libc = "0.2.159"
bytemuck = { version = "1.18.0", features = ["derive"] }
anyhow = { version = "1.0.89", default-features = false }

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
