[package]
name = "extern_traces_viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
egui_plot = "0.28.1"
ps4libdoc = { path = "../ps4libdoc" }
egui_tiles = "0.9.1"
itertools = "0.13.0"