[package]
name = "extern_traces_viewer"
version = "0.0.1"
edition = "2021"

build = "build.rs"

[dependencies]
eframe = "0.28.1"
egui_plot = "0.28.1"
ps4libdoc = { path = "../ps4libdoc" }
egui_tiles = "0.9.1"
rfd = "0.15.0"
clap = { version = "4.5.18", features = ["derive"] }
hex = "0.4.3"
egui_extras = { version = "0.28.0", features = ["image"] }