[package]
name = "pm4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bits = { path = "../bits" }
bits_macros = { path = "../bits_macros" }
anyhow = { version = "1.0.79", default-features = false }
strum = { version = "0.25.0", features = ["derive"], default-features = false }
pm4_internal_macros = { path = "../pm4_internal_macros" }
custom_debug = "0.6.1"
snafu = { version = "0.8.5", default-features = false, features = ["rust_1_81"] }

[dev-dependencies]
insta = { version = "1.33.0" }
snapshot_test_utils = { path = "../snapshot_test_utils" }
