[package]
name = "pm4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bits = { path = "../bits" }
bits_macros = { path = "../bits_macros" }
anyhow = "1.0.79"
byteorder = "1.5.0"
strum = { version = "0.25.0", features = ["derive"] }
pm4_internal_macros = { path = "../pm4_internal_macros" }

[dev-dependencies]
hex-literal = "0.4.1"
insta = { version = "1.33.0" }
