on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run make in Docker
        uses: docker://ghcr.io/0xcaff/ps4-sdk-images/goldhen:edge
        with:
          args: make -C packages/plugin

      - name: save artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: packages/plugin/target/**/*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4

      - run: |
          mkdir release
          mv build-artifacts/prx_final/extern_traces.prx

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
